# Generated by Django 2.2.4 on 2023-11-15 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='photo',
            field=models.ImageField(upload_to='photos/'),
        ),
    ]
